[package]
name = "minertim"
version = "1.0.0"
edition = "2021"

[lib]
name = "minertim"
path = "src/lib.rs"

[[bin]]
name = "minertim"
path = "src/bin/minertim.rs"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
log = "0.4.29"
env_logger = "0.11"
rustls = { version = "0.23", default-features = false, features = ["ring", "logging", "std", "tls12"] }
webpki-roots = "1.0"
ctrlc = "3.4"

[profile.release]
lto = true
opt-level = 3
strip = true
codegen-units = 1
